import React, { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { FileText, Download, Loader2, RefreshCw, Calendar } from 'lucide-react';
import jsPDF from 'jspdf';
import sanitationService from '../../services/sanitationService';

const WARD_NUMBER = 9;

const WeeklyReports = () => {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);

  const loadReports = async () => {
    try {
      setLoading(true);
      const data = await sanitationService.getReports();
      setReports(Array.isArray(data) ? data : []);
    } catch (err) {
      console.error(err);
      setReports([]);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadReports();
  }, []);

  const handleGenerate = async () => {
    try {
      setGenerating(true);
      await sanitationService.generateReport();
      await loadReports();
    } catch (err) {
      alert(err.message || 'Failed to generate report');
    } finally {
      setGenerating(false);
    }
  };

  const downloadPdf = (report) => {
    const doc = new jsPDF();
    const yStart = 20;
    let y = yStart;

    doc.setFontSize(18);
    doc.text('Weekly Sanitation Report', 14, y);
    y += 10;

    doc.setFontSize(10);
    doc.text(`Ward ${report.wardNumber || WARD_NUMBER} - Akkarakkunnu Anganwadi`, 14, y);
    y += 6;
    doc.text(`Period: ${report.weekStart ? new Date(report.weekStart).toLocaleDateString() : '-'} to ${report.weekEnd ? new Date(report.weekEnd).toLocaleDateString() : '-'}`, 14, y);
    y += 10;

    doc.setFontSize(12);
    doc.text('Summary', 14, y);
    y += 6;
    doc.setFontSize(10);
    doc.text(report.summary || 'No summary available.', 14, y, { maxWidth: 180 });
    y += 15;

    doc.setFontSize(11);
    doc.text(`Total cleaning tasks completed: ${report.totalCleaningTasksCompleted ?? 0}`, 14, y);
    y += 6;
    doc.text(`Total waste collected (kg): ${report.totalWasteCollectedKg ?? 0}`, 14, y);
    y += 6;
    doc.text(`Drainage issues detected: ${report.drainageIssuesDetected ?? 0}`, 14, y);
    y += 6;
    doc.text(`Hygiene status: ${report.hygieneStatus || 'N/A'}`, 14, y);
    y += 10;

    doc.setFontSize(9);
    doc.text(`Generated by: ${report.generatedBy || 'Sanitation Worker'}`, 14, y);
    doc.text(`Elikkullam Grama Panchayat, Pampady Block, Kottayam, Kerala`, 14, y + 5);

    doc.save(`Sanitation-Report-Ward${report.wardNumber || WARD_NUMBER}-${report.weekStart ? new Date(report.weekStart).toISOString().slice(0, 10) : 'weekly'}.pdf`);
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h2 className="text-2xl font-bold text-gray-900">Weekly Sanitation Reports</h2>
        <div className="flex items-center gap-2">
          <button
            onClick={loadReports}
            disabled={loading}
            className="flex items-center gap-2 px-4 py-2 border border-gray-300 rounded-lg hover:bg-gray-50"
          >
            <RefreshCw className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`} />
            Refresh
          </button>
          <button
            onClick={handleGenerate}
            disabled={generating}
            className="flex items-center gap-2 px-4 py-2 bg-primary-600 text-white rounded-lg hover:bg-primary-700 disabled:opacity-50"
          >
            {generating ? <Loader2 className="w-4 h-4 animate-spin" /> : <FileText className="w-4 h-4" />}
            Generate Weekly Report
          </button>
        </div>
      </div>

      <p className="text-gray-600 text-sm">
        Reports include total cleaning tasks completed, total waste collected, drainage issues, and hygiene status for Ward 9.
      </p>

      {loading ? (
        <div className="flex items-center justify-center py-12">
          <Loader2 className="w-8 h-8 animate-spin text-primary-600" />
        </div>
      ) : (
        <div className="bg-white rounded-xl shadow border border-gray-200 overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead className="bg-gray-50 border-b border-gray-200">
                <tr>
                  <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Period</th>
                  <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Tasks Done</th>
                  <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Waste (kg)</th>
                  <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Drainage Issues</th>
                  <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Hygiene</th>
                  <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Action</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-200">
                {reports.map((report) => (
                  <tr key={report._id} className="hover:bg-gray-50">
                    <td className="px-4 py-3 text-sm text-gray-700">
                      {report.weekStart && report.weekEnd
                        ? `${new Date(report.weekStart).toLocaleDateString()} - ${new Date(report.weekEnd).toLocaleDateString()}`
                        : '-'}
                    </td>
                    <td className="px-4 py-3 text-sm text-gray-900">{report.totalCleaningTasksCompleted ?? 0}</td>
                    <td className="px-4 py-3 text-sm text-gray-900">{report.totalWasteCollectedKg ?? 0}</td>
                    <td className="px-4 py-3 text-sm text-gray-900">{report.drainageIssuesDetected ?? 0}</td>
                    <td className="px-4 py-3 text-sm text-gray-700">{report.hygieneStatus || '-'}</td>
                    <td className="px-4 py-3">
                      <button
                        onClick={() => downloadPdf(report)}
                        className="flex items-center gap-1 text-primary-600 hover:text-primary-800 font-medium text-sm"
                      >
                        <Download className="w-4 h-4" />
                        Download PDF
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          {reports.length === 0 && (
            <p className="text-center py-8 text-gray-500">No reports yet. Click &quot;Generate Weekly Report&quot; to create one.</p>
          )}
        </div>
      )}
    </div>
  );
};

export default WeeklyReports;
